version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PASS=password
    networks:
      - app-net
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-net
    depends_on:
      - backend

  db:
    build: ./db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=restaurants
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d restaurants"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-net:
    name: restaurant_net
    driver: bridge

volumes:
  pgdata: