version: '3.8'

services:
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/public:/usr/share/nginx/html
    networks:
      - recommender-net

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=restaurants
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - db
    networks:
      - recommender-net

  db:
    build: ./db
    environment:
      - POSTGRES_DB=restaurants
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - recommender-net

volumes:
  postgres-data:

networks:
  recommender-net: